import org.antlr.v4.runtime.*;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Nimble {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        ANTLRFileStream str = ANTLRFileStream(args[0]);

    }
}
